apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: demo-gateway-mvc-app
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "*"

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: demo-mvc-app-service
spec:
  hosts:
  - "*"
  gateways:
  - demo-gateway-mvc-app
  http:
  - route:
    - destination:
        host: mvc-app-service
    retries:
      attempts: 3
      perTryTimeout: 5s
      retryOn: 5xx

apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "default"
  namespace: "default"
spec:
  mtls:
    mode: STRICT

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: default
  namespace: default
spec:
  host: "*.default.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
